export const userPreferences = {
  maxArticlesForAI: 15,

  highPriorityKeywords: [
    "java",
    "spring",
    "spring boot",
    "angular",
    "typescript",
    "javascript",
    "node",
    "node.js",
    "security",
    "vulnerability",
    "cve",
    "owasp",
    "docker",
    "postgresql",
    "github",
    "git",
    "ci/cd",
    "testing",
    "architecture",
    "backend",
    "frontend",
    "api",
    "rest",
    "ai",
    "artificial intelligence",
    "developer tools",
  ],

  mediumPriorityKeywords: [
    "performance",
    "release",
    "update",
    "best practices",
    "cloud",
    "database",
    "devops",
    "open source",
    "framework",
    "library",
  ],

  lowPriorityKeywords: [
    "funding",
    "startup",
    "partnership",
    "event",
    "conference",
    "webinar",
    "sponsored",
    "marketing",
  ],

  preferredSources: [
    "GitHub Blog",
    "Spring Blog",
    "Angular Blog",
    "Stack Overflow Blog",
  ],
};
